# Generated by Django 5.1.7 on 2025-03-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_orden_orderproduct_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="user",
        ),
    ]
